import type { LocaleCode } from "./i18n/locales";

const zh = `# Nova 富文本编辑器

一个 **插件化**、*多格式*、~~可定制~~ 的 Web 富文本编辑器：
Markdown / HTML 双向互转、自定义元素扩展、PC 与移动端自适应、开箱即用的国际化。

:::tip 立即体验
在空行输入 “/” 唤起命令面板，输入 “@” 提及成员，例如 @ada。
:::

## 能力清单

- [x] 常见富文本样式：加粗、斜体、~~删除线~~、\`行内代码\`
- [x] 自定义元素：提示块、@提及、评分、剧透
- [ ] 你的下一个插件

1. 渲染 Markdown / HTML / JSON
2. 插件可插拔：扩展、工具栏、命令、文案一起装卸
3. 三语切换：简体中文 · English · 日本語

> [!WARNING] 卸载插件会怎样？
> 关闭某个插件后，它带来的节点、工具按钮与 “/” 命令会同时消失，文档中的对应元素会被降级为纯文本。

## 表格

| 维度 | 说明 | 状态 |
| --- | --- | --- |
| 多格式 | md / html / json | 已支持 |
| 多语言 | zh-CN / en-US / ja-JP | 已支持 |
| 响应式 | 桌面工具条 + 移动端滑动工具条 | 已支持 |

\`\`\`ts
// 用一个数组就可以拼装出整个编辑器
const editor = useEditor({
  extensions: buildExtensions(resolvePlugins(enabled), placeholder),
});
\`\`\`

{{rating:4|整体体验}}

---

由 @nova 自动生成 · Markdown → HTML → Markdown 均可往返
`;

const en = `# Nova Rich Text Editor

A **pluggable**, *multi-format*, ~~hackable~~ rich text editor for the web:
two-way Markdown / HTML conversion, custom element extensions, responsive layout
and internationalization out of the box.

:::tip Try it now
Type "/" on an empty line for commands, and "@" to mention someone, e.g. @ada.
:::

## Feature checklist

- [x] Common styles: **bold**, *italic*, ~~strike~~, \`inline code\`
- [x] Custom elements: callout, @mention, rating, spoiler
- [ ] Your next plugin

1. Render Markdown / HTML / JSON
2. Pluggable plugins: extensions, toolbar, commands and copy in one unit
3. Three locales: 简体中文 · English · 日本語

> [!WARNING] What happens when a plugin is disabled?
> Its nodes, toolbar buttons and "/" commands disappear together, and its
> elements degrade to plain text.

## Table

| Dimension | Detail | Status |
| --- | --- | --- |
| Formats | md / html / json | Ready |
| Locales | zh-CN / en-US / ja-JP | Ready |
| Responsive | desktop ribbon + mobile scroll bar | Ready |

\`\`\`ts
const editor = useEditor({
  extensions: buildExtensions(resolvePlugins(enabled), placeholder),
});
\`\`\`

{{rating:5|Overall experience}}

---

Generated by @nova · Markdown → HTML → Markdown round trip
`;

const ja = `# Nova リッチテキストエディタ

**プラグイン式**・*マルチフォーマット*・~~拡張可能~~ な Web エディタ。
Markdown / HTML の双方向変換、カスタム要素、レスポンシブ、多言語対応。

:::tip 試してみましょう
空行で「/」を入力するとコマンド、「@」でメンション（例: @ada）。
:::

## 機能一覧

- [x] 基本書式：**太字**・*斜体*・~~打消し~~・\`コード\`
- [x] カスタム要素：コールアウト・メンション・評価
- [ ] あなたのプラグイン

1. Markdown / HTML / JSON を出力
2. プラグインの着脱（拡張・ツール・コマンド一式）
3. 3言語切替：简体中文 · English · 日本語

> [!WARNING] プラグインを無効化すると？
> ノード・ツール・「/」コマンドが同時に外れ、要素はテキストに変換されます。

## 表

| 項目 | 内容 | 状態 |
| --- | --- | --- |
| 形式 | md / html / json | 対応 |
| 言語 | zh-CN / en-US / ja-JP | 対応 |

\`\`\`ts
const editor = useEditor({
  extensions: buildExtensions(resolvePlugins(enabled), placeholder),
});
\`\`\`

{{rating:4|総合評価}}

---

@nova が生成 · Markdown → HTML → Markdown
`;

export const samples: Record<LocaleCode, string> = {
  "zh-CN": zh,
  "en-US": en,
  "ja-JP": ja,
};

export function getSample(locale: LocaleCode): string {
  return samples[locale] ?? en;
}
