import { TextAlign } from "@tiptap/extension-text-align";
import { TaskItem, TaskList } from "@tiptap/extension-list";
import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Code2,
  Heading1,
  Heading2,
  Heading3,
  List,
  ListChecks,
  ListOrdered,
  Minus,
  Quote,
  Type,
} from "lucide-react";
import { definePlugin } from "./registry";

const headingOptions = [
  { value: "p", labelKey: "p" },
  { value: "1", labelKey: "h1" },
  { value: "2", labelKey: "h2" },
  { value: "3", labelKey: "h3" },
];

const alignOptions = [
  { value: "left", labelKey: "alignLeft" },
  { value: "center", labelKey: "alignCenter" },
  { value: "right", labelKey: "alignRight" },
  { value: "justify", labelKey: "alignJustify" },
];

export const blocksPlugin = definePlugin({
  id: "blocks",
  name: "Blocks & Alignment",
  version: "2.0.0",
  author: "Nova Core",
  core: true,
  extensions: [
    TextAlign.configure({ types: ["heading", "paragraph"] }),
    TaskList,
    TaskItem.configure({ nested: true }),
  ],
  toolbar: [
    {
      id: "heading",
      titleKey: "heading",
      icon: Heading2,
      group: "block",
      kind: "select",
      options: headingOptions,
      run: (e, value) => {
        if (!value) return;
        if (value === "p") e.chain().focus().setParagraph().run();
        else e.chain().focus().toggleHeading({ level: Number(value) as 1 | 2 | 3 }).run();
      },
    },
    {
      id: "bullet",
      titleKey: "bullet",
      icon: List,
      group: "block",
      shortcut: "Mod+Shift+8",
      run: (e) => e.chain().focus().toggleBulletList().run(),
      isActive: (e) => e.isActive("bulletList"),
    },
    {
      id: "ordered",
      titleKey: "ordered",
      icon: ListOrdered,
      group: "block",
      shortcut: "Mod+Shift+7",
      run: (e) => e.chain().focus().toggleOrderedList().run(),
      isActive: (e) => e.isActive("orderedList"),
    },
    {
      id: "task",
      titleKey: "task",
      icon: ListChecks,
      group: "block",
      run: (e) => e.chain().focus().toggleTaskList().run(),
      isActive: (e) => e.isActive("taskList"),
    },
    {
      id: "quote",
      titleKey: "quote",
      icon: Quote,
      group: "block",
      run: (e) => e.chain().focus().toggleBlockquote().run(),
      isActive: (e) => e.isActive("blockquote"),
    },
    {
      id: "codeBlock",
      titleKey: "codeBlock",
      icon: Code2,
      group: "block",
      run: (e) => e.chain().focus().toggleCodeBlock().run(),
      isActive: (e) => e.isActive("codeBlock"),
    },
    {
      id: "divider",
      titleKey: "divider",
      icon: Minus,
      group: "block",
      run: (e) => e.chain().focus().setHorizontalRule().run(),
    },
    {
      id: "align",
      titleKey: "align",
      icon: AlignLeft,
      group: "align",
      kind: "select",
      options: alignOptions,
      run: (e, value) => {
        if (value) e.chain().focus().setTextAlign(value).run();
      },
    },
  ],
  suggestions: [
    {
      char: "/",
      getItems: () => [
        {
          id: "cmd.p",
          titleKey: "cmd.p",
          keywords: ["text", "paragraph", "正文", "段落"],
          icon: Type,
          group: "block",
          run: (e) => e.chain().focus().setParagraph().run(),
        },
        {
          id: "cmd.h1",
          titleKey: "cmd.h1",
          keywords: ["h1", "title", "标题"],
          icon: Heading1,
          group: "block",
          run: (e) => e.chain().focus().setHeading({ level: 1 }).run(),
        },
        {
          id: "cmd.h2",
          titleKey: "cmd.h2",
          keywords: ["h2", "heading", "标题"],
          icon: Heading2,
          group: "block",
          run: (e) => e.chain().focus().setHeading({ level: 2 }).run(),
        },
        {
          id: "cmd.h3",
          titleKey: "cmd.h3",
          keywords: ["h3", "heading", "标题"],
          icon: Heading3,
          group: "block",
          run: (e) => e.chain().focus().setHeading({ level: 3 }).run(),
        },
        {
          id: "cmd.bullet",
          titleKey: "cmd.bullet",
          keywords: ["ul", "list", "列表"],
          icon: List,
          group: "block",
          run: (e) => e.chain().focus().toggleBulletList().run(),
        },
        {
          id: "cmd.ordered",
          titleKey: "cmd.ordered",
          keywords: ["ol", "list", "列表"],
          icon: ListOrdered,
          group: "block",
          run: (e) => e.chain().focus().toggleOrderedList().run(),
        },
        {
          id: "cmd.task",
          titleKey: "cmd.task",
          keywords: ["todo", "check", "任务"],
          icon: ListChecks,
          group: "block",
          run: (e) => e.chain().focus().toggleTaskList().run(),
        },
        {
          id: "cmd.quote",
          titleKey: "cmd.quote",
          keywords: ["blockquote", "引用"],
          icon: Quote,
          group: "block",
          run: (e) => e.chain().focus().toggleBlockquote().run(),
        },
        {
          id: "cmd.code",
          titleKey: "cmd.code",
          keywords: ["code", "代码"],
          icon: Code2,
          group: "block",
          run: (e) => e.chain().focus().toggleCodeBlock().run(),
        },
        {
          id: "cmd.divider",
          titleKey: "cmd.divider",
          keywords: ["hr", "rule", "分割线"],
          icon: Minus,
          group: "block",
          run: (e) => e.chain().focus().setHorizontalRule().run(),
        },
        {
          id: "cmd.alignCenter",
          titleKey: "cmd.alignCenter",
          keywords: ["center", "居中"],
          icon: AlignCenter,
          group: "align",
          run: (e) => e.chain().focus().setTextAlign("center").run(),
        },
      ],
    },
  ],
  messages: {
    "zh-CN": {
      heading: "段落样式",
      p: "正文",
      h1: "一级标题",
      h2: "二级标题",
      h3: "三级标题",
      bullet: "无序列表",
      ordered: "有序列表",
      task: "任务列表",
      quote: "引用",
      codeBlock: "代码块",
      divider: "分割线",
      align: "对齐方式",
      alignLeft: "左对齐",
      alignCenter: "居中对齐",
      alignRight: "右对齐",
      alignJustify: "两端对齐",
      "cmd.p": "正文段落",
      "cmd.h1": "一级标题",
      "cmd.h2": "二级标题",
      "cmd.h3": "三级标题",
      "cmd.bullet": "无序列表",
      "cmd.ordered": "有序列表",
      "cmd.task": "任务清单",
      "cmd.quote": "引用块",
      "cmd.code": "代码块",
      "cmd.divider": "分割线",
      "cmd.alignCenter": "居中对齐",
    },
    "en-US": {
      heading: "Block type",
      p: "Text",
      h1: "Heading 1",
      h2: "Heading 2",
      h3: "Heading 3",
      bullet: "Bullet list",
      ordered: "Ordered list",
      task: "Task list",
      quote: "Quote",
      codeBlock: "Code block",
      divider: "Divider",
      align: "Alignment",
      alignLeft: "Align left",
      alignCenter: "Align center",
      alignRight: "Align right",
      alignJustify: "Justify",
      "cmd.p": "Plain text",
      "cmd.h1": "Heading 1",
      "cmd.h2": "Heading 2",
      "cmd.h3": "Heading 3",
      "cmd.bullet": "Bullet list",
      "cmd.ordered": "Ordered list",
      "cmd.task": "Task list",
      "cmd.quote": "Quote",
      "cmd.code": "Code block",
      "cmd.divider": "Divider",
      "cmd.alignCenter": "Center align",
    },
    "ja-JP": {
      heading: "ブロック種別",
      p: "本文",
      h1: "見出し 1",
      h2: "見出し 2",
      h3: "見出し 3",
      bullet: "箇条書き",
      ordered: "番号リスト",
      task: "タスク",
      quote: "引用",
      codeBlock: "コードブロック",
      divider: "区切り線",
      align: "配置",
      alignLeft: "左寄せ",
      alignCenter: "中央",
      alignRight: "右寄せ",
      alignJustify: "両端揃え",
      "cmd.p": "本文",
      "cmd.h1": "見出し 1",
      "cmd.h2": "見出し 2",
      "cmd.h3": "見出し 3",
      "cmd.bullet": "箇条書き",
      "cmd.ordered": "番号リスト",
      "cmd.task": "タスクリスト",
      "cmd.quote": "引用",
      "cmd.code": "コード",
      "cmd.divider": "区切り線",
      "cmd.alignCenter": "中央揃え",
    },
  },
});
