import { Highlight } from "@tiptap/extension-highlight";
import { Color } from "@tiptap/extension-color";
import { TextStyle } from "@tiptap/extension-text-style";
import { Subscript } from "@tiptap/extension-subscript";
import { Superscript } from "@tiptap/extension-superscript";
import { Underline } from "@tiptap/extension-underline";
import {
  Bold,
  Code,
  Eraser,
  EyeOff,
  Highlighter,
  Italic,
  Palette,
  Strikethrough,
  Underline as UnderlineIcon,
} from "lucide-react";
import { definePlugin } from "./registry";
import { Spoiler } from "../extensions/Spoiler";

const COLORS = [
  { value: "#e11d48", labelKey: "color.red" },
  { value: "#f59e0b", labelKey: "color.orange" },
  { value: "#10b981", labelKey: "color.green" },
  { value: "#3b82f6", labelKey: "color.blue" },
  { value: "#8b5cf6", labelKey: "color.purple" },
  { value: "#111827", labelKey: "color.dark" },
  { value: "default", labelKey: "color.default" },
];

export const marksPlugin = definePlugin({
  id: "marks",
  name: "Text Styles",
  version: "2.1.0",
  author: "Nova Core",
  core: true,
  extensions: [
    Underline,
    Highlight.configure({ multicolor: false }),
    TextStyle,
    Color,
    Subscript,
    Superscript,
    Spoiler,
  ],
  toolbar: [
    {
      id: "bold",
      titleKey: "bold",
      icon: Bold,
      group: "inline",
      shortcut: "Mod+B",
      run: (e) => e.chain().focus().toggleBold().run(),
      isActive: (e) => e.isActive("bold"),
    },
    {
      id: "italic",
      titleKey: "italic",
      icon: Italic,
      group: "inline",
      shortcut: "Mod+I",
      run: (e) => e.chain().focus().toggleItalic().run(),
      isActive: (e) => e.isActive("italic"),
    },
    {
      id: "underline",
      titleKey: "underline",
      icon: UnderlineIcon,
      group: "inline",
      shortcut: "Mod+U",
      run: (e) => e.chain().focus().toggleUnderline().run(),
      isActive: (e) => e.isActive("underline"),
    },
    {
      id: "strike",
      titleKey: "strike",
      icon: Strikethrough,
      group: "inline",
      run: (e) => e.chain().focus().toggleStrike().run(),
      isActive: (e) => e.isActive("strike"),
    },
    {
      id: "code",
      titleKey: "code",
      icon: Code,
      group: "inline",
      shortcut: "Mod+E",
      run: (e) => e.chain().focus().toggleCode().run(),
      isActive: (e) => e.isActive("code"),
    },
    {
      id: "highlight",
      titleKey: "highlight",
      icon: Highlighter,
      group: "inline",
      run: (e) => e.chain().focus().toggleHighlight().run(),
      isActive: (e) => e.isActive("highlight"),
    },
    {
      id: "color",
      titleKey: "color",
      icon: Palette,
      group: "inline",
      kind: "color",
      options: COLORS.map((c) => ({ ...c, swatch: c.value })),
      run: (e, value) => {
        if (!value) return;
        if (value === "default") e.chain().focus().unsetColor().run();
        else e.chain().focus().setColor(value).run();
      },
    },
    {
      id: "spoiler",
      titleKey: "spoiler",
      icon: EyeOff,
      group: "inline",
      run: (e) => (e.chain().focus() as any).toggleSpoiler().run(),
      isActive: (e) => e.isActive("spoiler"),
    },
    {
      id: "clear",
      titleKey: "clear",
      icon: Eraser,
      group: "inline",
      run: (e) => e.chain().focus().unsetAllMarks().clearNodes().run(),
    },
  ],
  messages: {
    "zh-CN": {
      bold: "加粗",
      italic: "斜体",
      underline: "下划线",
      strike: "删除线",
      code: "行内代码",
      highlight: "高亮",
      color: "文字颜色",
      spoiler: "剧透",
      clear: "清除格式",
      "color.red": "红色",
      "color.orange": "橙色",
      "color.green": "绿色",
      "color.blue": "蓝色",
      "color.purple": "紫色",
      "color.dark": "墨色",
      "color.default": "默认",
    },
    "en-US": {
      bold: "Bold",
      italic: "Italic",
      underline: "Underline",
      strike: "Strikethrough",
      code: "Inline code",
      highlight: "Highlight",
      color: "Text color",
      spoiler: "Spoiler",
      clear: "Clear format",
      "color.red": "Red",
      "color.orange": "Orange",
      "color.green": "Green",
      "color.blue": "Blue",
      "color.purple": "Purple",
      "color.dark": "Ink",
      "color.default": "Default",
    },
    "ja-JP": {
      bold: "太字",
      italic: "斜体",
      underline: "下線",
      strike: "打消し線",
      code: "インラインコード",
      highlight: "ハイライト",
      color: "文字色",
      spoiler: "ネタバレ",
      clear: "書式クリア",
      "color.red": "赤",
      "color.orange": "オレンジ",
      "color.green": "緑",
      "color.blue": "青",
      "color.purple": "紫",
      "color.dark": "墨",
      "color.default": "既定",
    },
  },
});
